---
title: ""
date-modified: last-modified
---

## 프로그램의 개요

-   **서울시교육청**과 **서울대학교 미래교육센터**가 운영하는 2025년 하반기 서울대학교 **마이크로디그리형 연수** 프로그램

    -   마이크로디그리형 연수랑 연수를 이수한 교사에게 학점을 인정하는 연수

-   「서울대학교 특별수강생 수학에 관한 규정」의 「특별수강생 학점 인정 처리 기준」에 근거하여, 특별수강생으로 취득한 학점은 향후 본교 대학원 동일과정 및 동일전공으로 입학한 경우에 본교 학점인정절차에 따라 12학점 이내에서 학점인정 가능

    -   45시간 연수를 이수한 경우 석사 학위 이수 학점 중 3학점 인정

    -   교과목 성적이 B0 이상인 경우에 한하며, 취득성적 그대로 학적부에 등재 및 성적평점평균에 합산함

## 프로그램의 목표

-   AI/데이터사이언스의 기술 및 원리와 사회과(일반사회, 역사, 지리, 윤리)의 구체적인 주제(인구)를 결합한 융합형 수업 콘텐츠 설계 능력을 함양한다.

-   오픈소스 프로그래밍 언어(R), 마크다운 기반 디지털 출판 도구(Quarto), 서버형 웹 앱 개발 도구(Shiny)를 활용한 인터랙티브 교수ㆍ학습 웹 앱의 개발 역량을 함양한다.

-   생성형 AI를 인터랙티브 교수ㆍ학습 웹 앱과 결합하는 다양한 방안에 대해 모색한다.

## 주요 내용

-   교사의 AIㆍ디지털 역량: 1일

-   세 가지 사이언스의 융합과 오픈소스 프로그래밍: 5일

-   인구 현상과 인문사회 콘텐츠: 2일

-   인터랙티브 교수ㆍ학습 웹 앱의 디자인: 3일

-   인터랙티브 교수ㆍ학습 웹 앱의 구현: 4일

## 진행

-   프로그램 총괄 및 이론 강의

    -   [이상일](https://sangillee.snu.ac.kr/) 교수([서울대학교 사범대학 지리교육과](https://geoedu.snu.ac.kr/))

-   프로그램 평가

    -   이소영 교수([가톨릭관동대학교 사범대학 지리교육과](https://www.cku.ac.kr/geography/index.do))

-   실습

    -   김우형(서울대학교 지리교육과 석사과정)

    -   박서우(서울대학교 지리교육과 석사과정)

## 주관

-   [서울대학교](https://www.snu.ac.kr/) [학습과학연구소](https://ls.snu.ac.kr/) [미래교육혁신센터](https://ls.snu.ac.kr/sub_center/center4.php)

## 일시 및 장소

-   2025년 12월 29일 \~ 2026년 1월 16일 오후 6\~9시

-   서울대학교 사범대학 교육정보관 VR-LAB(10-1동 316호)

## 일정

### 사전 학습

-   R과 RStudio

-   R과 데이터사이언스 과정

### 1주차(2025년 12월 29일 \~ 2026년 1월 2일)

-   12월 29일(월): 교사의 AIㆍ디지털 역량

    -   강의: 교사의 AIㆍ디지털 역량

-   12월 30일(화): 세 가지 사이언스의 융합과 오픈소스 프로그래밍 1

    -   강의: 세 가지 사이언스의 융합

-   12월 31일(수): 세 가지 사이언스의 융합과 오픈소스 프로그래밍 2

    -   강의 및 실습: 데이터 불러오기, 정돈하기, 변형하기

-   1월 1일(목): 세 가지 사이언스의 융합과 오픈소스 프로그래밍 3

    -   [비대면 수업]{style="color:red"}: R 프로그래밍 복습

-   1월 2일(금): 세 가지 사이언스의 융합과 오픈소스 프로그래밍 4

    -   강의 및 실습: 데이터 시각화하기, 수집하기

### 2주차(2026년 1월 5일 \~ 9일)

-   1월 5일(월): 세 가지 사이언스의 융합과 오픈소스 프로그래밍 5

    -   강의 및 실습: **Quarto**를 활용한 대시보드 만들기

-   1월 6일(화): 인구 현상과 인문사회 콘텐츠 1

    -   강의: 인구 데이터, 인구 성장, 인구 분포

-   1월 7일(수): 인구 현상과 인문사회 콘텐츠 2

    -   강의: 인구 구조, 인구 동태, 인구 이동

-   1월 8일(목): 인터랙티브 교수ㆍ학습 웹 앱의 디자인 1

    -   강의 및 실습: 인터랙티브 및 지리공간 시각화

-   1월 9일(금): 인터랙티브 교수ㆍ학습 웹 앱의 디자인 2

    -   강의 및 실습: **Shiny**를 활용한 웹 앱 제작

### 3주차(2026년 1월 12일 \~ 16일)

-   1월 12일(월): 인터랙티브 교수ㆍ학습 웹 앱의 디자인 3

    -   워크숍: 웹 앱 디자인 발표 및 피드백

-   1월 13일(화): 인터랙티브 교수ㆍ학습 웹 앱의 구현 1

    -   [비대면 수업]{style="color:red"}: **LLM**과 웹 앱

-   1월 14일(수): 인터랙티브 교수ㆍ학습 웹 앱의 구현 2

    -   워크숍: 제작 및 배포

-   1월 15일(목): 인터랙티브 교수ㆍ학습 웹 앱의 구현 3

    -   워크숍: 제작 및 배포

-   1월 16일(금): 인터랙티브 교수ㆍ학습 웹 앱의 구현 4

    -   워크숍: 최종 발표
