---
title: ""
date-modified: last-modified
---

## 사전 학습

+-------------------------+-------------------------------------------------------+
| 주제                    | 실습 자료                                             |
+=========================+=======================================================+
| R과 RStudio             | [Lab_01](Lab_01.qmd)                                  |
|                         |                                                       |
|                         | [동영상](https://www.youtube.com/watch?v=tcSlQFYU_uQ) |
+-------------------------+-------------------------------------------------------+
| R과 데이터사이언스 과정 | [Lab_02](Lab_02.qmd)                                  |
+-------------------------+-------------------------------------------------------+

## 1주차 (2025년 12월 29일 \~ 2026년 1월 2일)

+-------------------------------------------+----------------------------------------------------+--------------------------------+---------------------------------+
| 날짜                                      | 주제                                               | 강의 자료                      | 실습 자료                       |
+:=========================================:+====================================================+:==============================:+:===============================:+
| 12월 29일 <br> (월)                       | 교사의 AIㆍ디지털 역량과 세 가지 사이언스의 융합 1 | [연수 소개](Lecture_0.qmd)     |                                 |
|                                           |                                                    |                                |                                 |
|                                           | -   교사의 AIㆍ디지털 역량                         | [Lecture_1_1](Lecture_1_1.qmd) |                                 |
+-------------------------------------------+----------------------------------------------------+--------------------------------+---------------------------------+
| 12월 30일 <br> (화)                       | 교사의 AIㆍ디지털 역량과 세 가지 사이언스의 융합 2 | [Lecture_1_2](Lecture_1_2.qmd) |                                 |
|                                           |                                                    |                                |                                 |
|                                           | -   세 가지 사이언스의 융합                        |                                |                                 |
+-------------------------------------------+----------------------------------------------------+--------------------------------+---------------------------------+
| 12월 31일 <br> (수)                       | 오픈소스(**R**) 프로그래밍 1                       | [Lecture_1_3](Lecture_1_3.qmd) | [Lab_03 불러오기](Lab_03.qmd)   |
|                                           |                                                    |                                |                                 |
|                                           | -   데이터 불러오기ㆍ정돈하기ㆍ변형하기            |                                | [Lab_04 정돈하기](Lab_04.qmd)   |
|                                           |                                                    |                                |                                 |
|                                           |                                                    |                                | [Lab_05 변형하기](Lab_05.qmd)   |
+-------------------------------------------+----------------------------------------------------+--------------------------------+---------------------------------+
| **1월 1일** <br> **(목)** <br> **비대면** | 오픈소스(**R**) 프로그래밍 2                       | [Lecture_1_4](Lecture_1_4.qmd) |                                 |
|                                           |                                                    |                                |                                 |
|                                           | -   복습: 데이터 탐색하기                          |                                |                                 |
+-------------------------------------------+----------------------------------------------------+--------------------------------+---------------------------------+
| 1월 2일 <br> (금)                         | 오픈소스(**R**) 프로그래밍 3                       | [Lecture_1_5](Lecture_1_5.qmd) | [Lab_06_시각화하기](Lab_06.qmd) |
|                                           |                                                    |                                |                                 |
|                                           | -   데이터 시각화하기ㆍ수집하기                    |                                | [Lab_07_수집하기](Lab_07.qmd)   |
+-------------------------------------------+----------------------------------------------------+--------------------------------+---------------------------------+

: {tbl-colwidths="\[14,46,19,21\]"}

## 2주차 (2026년 1월 5일 \~ 9일)

+-------------------------------------------+-----------------------------------------+----------------------------------------+-----------------------------+
| 날짜                                      | 주제                                    | 강의 자료                              | 실습 자료                   |
+:=========================================:+=========================================+:======================================:+:===========================:+
| 1월 5일 <br> (월)                         | 오픈소스(**R**) 프로그래밍 4            | [Lecture_2_1](Lecture_2_1.qmd)         | [Lab_08_Quarto](Lab_08.qmd) |
|                                           |                                         |                                        |                             |
|                                           | -   **Quarto**를 활용한 대시보드 만들기 |                                        |                             |
+-------------------------------------------+-----------------------------------------+----------------------------------------+-----------------------------+
| **1월 6일** <br> **(화)** <br> **비대면** | 인구 현상과 인문사회 콘텐츠 1           | [Lecture_2_2_1](Lecture_2_2_1.qmd)     |                             |
|                                           |                                         |                                        |                             |
|                                           | -   인구 데이터, 인구 성장, 인구 분포   | [동영상](https://youtu.be/z-FzLRf-E34) |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [Lecture_2_2_2](Lecture_2_2_2.qmd)     |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [동영상](https://youtu.be/z-ZCGRlgGkc) |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [Lecture_2_2_3](Lecture_2_2_3.qmd)     |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [동영상](https://youtu.be/yMq3DZibX_s) |                             |
+-------------------------------------------+-----------------------------------------+----------------------------------------+-----------------------------+
| **1월 7일** <br> **(수)** <br> **비대면** | 인구 현상과 인문사회 콘텐츠 2           | [Lecture_2_3_1](Lecture_2_3_1.qmd)     |                             |
|                                           |                                         |                                        |                             |
|                                           | -   인구 구조, 인구 동태, 인구 이동     | [동영상](https://youtu.be/cUE9r2OpCSg) |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [Lecture_2_3_2](Lecture_2_3_2.qmd)     |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [동영상](https://youtu.be/sqpsciokWEg) |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [Lecture_2_3_3](Lecture_2_3_3.qmd)     |                             |
|                                           |                                         |                                        |                             |
|                                           |                                         | [동영상](https://youtu.be/njXl7k1KTvM) |                             |
+-------------------------------------------+-----------------------------------------+----------------------------------------+-----------------------------+
| 1월 8일 <br> (목)                         | 인터랙티브 교수ㆍ학습 웹 앱의 디자인 1  |                                        |                             |
|                                           |                                         |                                        |                             |
|                                           | -   인터랙티브 및 지리공간적 시각화     |                                        |                             |
+-------------------------------------------+-----------------------------------------+----------------------------------------+-----------------------------+
| 1월 9일 <br> (금)                         | 인터랙티브 교수ㆍ학습 웹 앱의 디자인 2  |                                        |                             |
|                                           |                                         |                                        |                             |
|                                           | -   **Shiny**를 활용한 웹 앱 제작       |                                        |                             |
+-------------------------------------------+-----------------------------------------+----------------------------------------+-----------------------------+

: {tbl-colwidths="\[14,46,19,21\]"}

## 3주차 (2026년 1월 12일 \~ 16일)

+--------------------------------------------+----------------------------------------+-----------+-----------+
| 날짜                                       | 주제                                   | 강의 자료 | 실습 자료 |
+:==========================================:+========================================+:=========:+:=========:+
| 1월 12일 <br> (월)                         | 인터랙티브 교수ㆍ학습 웹 앱의 디자인 3 |           |           |
|                                            |                                        |           |           |
|                                            | -   **R 프로그래밍 시험**              |           |           |
|                                            | -   웹 앱 디자인 발표 및 피드백        |           |           |
+--------------------------------------------+----------------------------------------+-----------+-----------+
| **1월 13일** <br> **(화)** <br> **비대면** | 인터랙티브 교수ㆍ학습 웹 앱의 제작 1   |           |           |
+--------------------------------------------+----------------------------------------+-----------+-----------+
| 1월 14일 <br> (수)                         | 인터랙티브 교수ㆍ학습 웹 앱의 제작 2   |           |           |
+--------------------------------------------+----------------------------------------+-----------+-----------+
| 1월 15일 <br> (목)                         | 인터랙티브 교수ㆍ학습 웹 앱의 제작 3   |           |           |
+--------------------------------------------+----------------------------------------+-----------+-----------+
| 1월 16일 <br> (금)                         | 인터랙티브 교수ㆍ학습 웹 앱의 제작 4   |           |           |
|                                            |                                        |           |           |
|                                            | -   **최종 발표**                      |           |           |
+--------------------------------------------+----------------------------------------+-----------+-----------+

: {tbl-colwidths="\[14,46,19,21\]"}
