---
title: ""
date-modified: last-modified
---

> 웹 접근이 가능한 참고문헌을 중심으로 정리하였습니다. 문건 아래에 짧막한 코멘트를 달아 두었으니 참고바랍니다.

## 데이터사이언스와 R

-   Wickham, Hadley, Mine Çetinkaya-Rundel, and Garrett Grolemund, 2023, [*R for Data Science: Import, Tidy, Transform, Visualize, and Model Data*](https://r4ds.hadley.nz/)*,* 2nd edition, Boston: O’Reilly.

    -   바이블과 같은 책입니다. 필독을 권합니다. 특히 "Whole game"이라는 장의 8개 절을 살펴보세요. 강의와 실습의 많은 내용이 이 곳으로부터 나왔습니다.

-   Baumer, Benjamin, Daniel T. Kaplan, and Nicholas J. Horton. 2024. [*Modern Data Science with R*](https://mdsr-book.github.io/mdsr3e/), 3rd edition, Boca Raton: CRC Press.

-   Irizarry, Rafael A. 2024. [*Introduction to Data Science: Data Wrangling and Visualization with R*](https://rafalab.dfci.harvard.edu/dsbook-part-1/). 2nd edition, Boca Raton: CRC Press.

-   Bonnell, Jerry, and Mitsunori Ogihara. 2023. [*Exploring Data Science with R and the Tidyverse*](https://ds4world.cs.miami.edu/). 1st edition. Chapman; Hall/CRC.

-   김길환, 2025, [R 프로그래밍(개정판)](https://kilhwan.github.io/rprogramming/), 웹북

    -   상명대학교 김길환 교수님께서 쓰신 R 기초 웹북입니다. 방대한 주제를 다루고 있습니다. 훌륭한 책이지만 형식이 좀 올드한 느낌이 있긴 합니다. 그래도 한글로 된 R 웹북이 매우 드물다는 의미에서 충분한 가치가 있는 책입니다.

-   한국 R 사용자회, [데이터 과학을 지탱하는 기본기](https://r2bit.com/book_analytics/), 웹북

    -   한국 R 사용자회의 무료 웹북 중의 하나입니다. 데이터 과학과 관련된 다양한 내용으로 구성이 되어 있습니다. 프로그래밍 섹션이 R과 관련된 내용입니다.

-   백영민, 2023, [R 기반 데이터 과학: 타이디버스(tidyverse) 접근](https://www.yes24.com/Product/Goods/123807713), 서울: 한나래아카데미.

    -   Base R에 기반한 R 개론서는 이제 의미가 없습니다. 완전히 Tidyverse에 입각해 쓰여진 한글 R 개론서가 많지 않고 있다 하더라도 부실한 경우가 많은데, 연세대학교 백영민 교수님의 이 책은 그래도 좋은 편에 속합니다. 단, 파이프 오퍼레이터의 기호를 최근 표준이 되고 있는 \|\>이 아니라 %\>%을 사용한 것이 조금 불만입니다.

## 쿼토 Quarto

-   [Quarto 웹사이트](https://quarto.org/)

    -   쿼토에 대한 가장 좋은 참고문헌은 공식 웹사이트에 있는 내용입니다. 좀 복잡하게 구성되어 있는 느낌이 들긴 하지만 방대한 내용이 잘 다루어져 있습니다.

    -   웹저작의 기초: 마크다운의 기초, 그림, 테이블, 다이어그램, 비디오의 삽입 등 다양한 Quarto 다큐먼트 작성의 기본 사항

        -   [Guide의 Authoring 부분](https://quarto.org/docs/authoring/markdown-basics.html)

    -   다양한 웹 다큐먼트 만들기

        -   [대시보드](https://quarto.org/docs/dashboards/)

        -   [프레젠테이션](https://quarto.org/docs/presentations/)

        -   [웹사이트](https://quarto.org/docs/websites/)

        -   [웹북](https://quarto.org/docs/books/)

    -   기타 사항

        -   [웹 출간](https://quarto.org/docs/publishing/)

## 샤이니 Shiny

-   [Shiny 웹사이트](https://shiny.posit.co/)

    -   샤이니에 대한 가장 좋은 참고문헌은 공식 웹사이트에 있는 내용입니다.
    -   특히 [Shiny for R](https://shiny.posit.co/r/)을 참고하세요.

-   Wickham, Hadley, 2021, [*Mastering Shiny: Build Interactive Apps, Reports, and Dashboards Powered by R*](https://mastering-shiny.org/)*,* Sebastopol, CA: O’REILLY. (이영록 옮김, 2022, [R 사용자를 위한 Shiny 마스터 가이드](https://www.yes24.com/Product/Goods/116598818), 서울: 인사이트.)

    -   해들리 위컴이 쓴 샤이니 관련 바이블입니다. 원문 웹북을 보기를 권하지만 우선은 번역서도 좋을 것 같습니다.

-   Granjon, David, 2022, [*Outstanding User Interfaces with Shiny*](https://unleash-shiny.rinterface.com/), Boaca Raton: CRC Press.

-   Fay, Colin, Vincent Guyader, Sebastien Rochette, and Cervan Girard. 2022, [*Engineering Production-Grade Shiny Apps*](https://engineering-shiny.org/), Boca Raton: CRC Press.

## 시각화

-   Wickham, Hadley. 2016. [*ggplot2: Elegant Graphics for Data Analysis*](https://ggplot2-book.org/). 2nd edition, Switzerland: Springer. (박진수 옮김, 2017. [R로 분석한 데이터를 멋진 그래픽으로 ggplot2](https://www.yes24.com/Product/Goods/57248968). 부천: 프리렉.)

    -   위의 영문 웹북으로 들어가면 이미 3판이 업데이트되어 있음을 확인할 수 있습니다. 번역서는 2판 기준이므로 원서 웹북을 읽기를 권합니다.

-   Sievert, C., 2020, [*Interactive Web-Based Data Visualization with R, plotly, and shiny*](https://plotly-r.com/index.html), Boca Raton: CRC Press.

    -   훌륭한 책입니다. 샤이니를 일부 다루고 있다는 것도 좋습니다.

-   Kabacoff, Robert, 2024, [*Modern Data Visualization with R*](https://rkabacoff.github.io/datavis/), Boca Raton: CRC Press.

-   Alexander, Rohan. 2023. [*Telling Stories with Data With Applications in R*](https://tellingstorieswithdata.com/). Boca Raton: CRC Press.

-   Healy, Kieran. 2019. [*Data Visualization: A Practical Introduction*](https://socviz.co/). Princeton: Princeton University Press.

-   Dougherty, Jack, and Ilya Ilyankou, 2025, [*Hands-on Data Visualization: Interactive Storytelling from Spreadsheets to Code*](https://handsondataviz.org/), Boston: O’Reilly. (김태현 옮김, 2022, [핸즈온 데이터 시각화](https://www.yes24.com/product/goods/110225484), 서울: 한빛미디어.)

-   Yau, Nathan. 2024. [*Visualize This: The FlowingData Guide to Design, Visualization, and Statistics*](https://www.google.co.kr/books/edition/Visualize_This/CB9XRIv9oigC?hl=ko&gbpv=0). 2nd edition, Hoboken: Wiley. (한상택 옮김, 2025, [데이터리터리시를 높이는 데이터 시각화: 숫자를 메시지로 바꾸는 스토리텔링과 그래프 작성](https://www.yes24.com/product/goods/152302455), 서울: 인사이트.)

-   Allchin, Carl. 2021. [*Communicating with Data: Making Your Case with Data*](https://www.google.co.kr/books/edition/Communicating_with_Data/4eZFEAAAQBAJ?hl=ko&gbpv=0). O'Reilly Media. (이한호 옮김, 2022, [데이터로 전문가처럼 말하기: 효율적 의사 전달을 위한 데이터 시각화와 비즈니스 스토리텔링의 기술](https://www.yes24.com/product/goods/112230753), 서울: 한빛미디어.)

-   Wilke, Claus. 2019. [Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures](https://clauswilke.com/dataviz/). O'Reilly Media. (권혜정 옮김, 2020, [데이터 시각화 교과서: 데이터 분석의 본질을 살리는 그래프와 차트 제작의 기본 원리와 응용](https://www.yes24.com/product/goods/87631760), 안양: 책만.)

-   Cairo, Alberto. 2016. [*The Truthful Art: Data, Charts, and Maps for Communication*](https://www.google.co.kr/books/edition/The_Truthful_Art/8dKKCwAAQBAJ?hl=ko&gbpv=0). New Riders. (이제원 옮김, 2019, [진실을 드러내는 데이터 시각화의 과학과 예술](https://www.yes24.com/product/goods/72254343), 서울: 인사이트.)

-   한국R사용자회, 2022, [데이터 시각화](https://r2bit.com/book_viz/), 오픈전자책.

    -   한글로된 데이터 시각화 개론서로, 시각화를 위한 기본 개념에 대한 설명에서부터 ggplot2 패키지의 사용법까지 포함되어 있습니다. 흥미로운 예제도 살펴볼만 합니다.

-   이기준, 2023, [Plotly로 시작하는 인터렉티브 데이터 시각화 in R & 파이썬](https://www.yes24.com/Product/Goods/123706075), 제이펍.

    -   한글로된 Plotly 시각화 도서입니다. 제대로 살펴보진 못했지만 책이 짜임새 있어 보이고 R의 랩퍼 패키지를 활용한 예제가 제시되어 있다는 점에서 많은 도움이 될 것으로 생각됩니다.

## 텍스트 마이닝과 자연어처리

-   한국 R 사용자회ㆍ안도현, 2022, [R 텍스트마이닝](https://r2bit.com/book_tm/), 오픈전자책.

    -   한국 R 사용자회의 무료 웹북 중의 하나입니다. Tidyverse와 파이프 연산자에 기반하고 있습니다. 좋은 책입니다.

-   김영우, 2021, [쉽게 배우는 R 텍스트 마이닝](https://www.yes24.com/Product/Goods/97126355), 서울: 이지스퍼블리싱.

    -   이렇게 훌륭한 R 기반 텍스트 마이닝 책이 있다는 것이 너무 감사할 뿐입니다. 웹복이 아닌 것이 아쉬울 뿐입니다.
